### ISSUE TITLE
Streamer mode isn't functioning & port already used error window

### ISSUE THREAD

**Issue by LazyRen** [cohstats/coh2stats#242]
1. Both general mode & Twitch extension works fine, but Streamer mode (with OBS) doesn't show anything.

It sometimes work after changing server port few times back and forth, but it's not the definite solution.
And even if it does, only the rank is shown on wrong place

e.g) Notice Rank 78 & 18 shown on weird position (My setting for the layout is Left)
![화면 캡처 2022-08-13 161432](https://user-images.githubusercontent.com/8989837/184473368-c373378d-99a5-4f2c-a150-f848f55cdf24.png)

2. Every time I change the port, I get below error message. I think it would be better to consume the exception and show it with simple one line message on the existing setting window would be much better.
![화면 캡처 2022-08-13 161244](https://user-images.githubusercontent.com/8989837/184473398-9f3b7e93-ab2e-4793-a843-40da8c2412ee.png)

Love your site & desktop app. Cheers for your work. Thank you.

**Comment by petrvecera** [comment]
Hi, thanks for the report! This is most likely due to another instance of the app running or there is crashed detached process running on the background :( Please try to always quit the app via the X button or menu and not via ALT+F4 or things like that. 

Also I think restart of the PC in this case should help. 

We want to migrate to a different build process of the desktop app because now we are using Electron-forge which doesn't allow us to do things like limit the amount of running instances / or is not great in handling those things.

**Comment by LazyRen** [comment]
Thank you for your answer @petrvecera, I don't think it's problem of a duplicate instance of the app running because it always prints the error msg even if it's the first instance of the app I launched. And it always happens no matter what port # I choose.

However, I'm looking forward to seeing the next desktop app and hopefully, the situation would be eased by then.

**Comment by petrvecera** [comment]
This has been fixed in the latest release of desktop app.
